-- Migration 004: Add idempotency key for payments
-- Purpose: Prevent double-charging if payment API is called twice
-- Implementation: Add idempotencyKey (UUID) unique field to payments table
-- Author: Phase 2 remediation

BEGIN;

-- Add idempotencyKey column to payments table
-- This field stores a UUID generated by the client (or server) before calling payment API
-- If the same idempotencyKey is used twice, second attempt returns cached result
-- Prevents double-charge if payment gateway is called multiple times for same order

ALTER TABLE payments
ADD COLUMN "idempotencyKey" VARCHAR(36) UNIQUE;

-- Add index for fast lookups by idempotency key
CREATE INDEX IF NOT EXISTS idx_payments_idempotency_key
ON payments("idempotencyKey");

-- Add column to track payment attempts (for debugging)
ALTER TABLE payments
ADD COLUMN "attemptCount" INT DEFAULT 1;

-- Add column to track if payment was recovered from idempotent lookup
ALTER TABLE payments
ADD COLUMN "wasIdempotent" BOOLEAN DEFAULT FALSE;

-- Add index on (orderId, status) for "get payment of order"
CREATE INDEX IF NOT EXISTS idx_payments_order_status
ON payments("orderId", "status");

COMMIT;
